name: build

on: 
  push:
      branches-ignore:
        - master 
  pull_request:

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm32v7
          push: false
          tags: chadhutchins182/route53-dynamic-dns-arm32v7:latest
          build-args: |
            VERSION=v3.2.1
            PLATFORM=armv7-generic