name: Pull Request CI

on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build & Test Code

    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@v2
    
    # Set version of node to use
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    # This command is similar to npm install, except it's meant to be used in
    # automated environments such as test platforms, continuous integration,
    # and deployment -- or any situation where you want to make sure you're
    # doing a clean install of your dependencies.    
    - run: npm ci
    
    # Run build script.  If it doesn't exist, don't error
    - run: npm run build --if-present

    # Run tests  
    - run: npm test
